### ISSUE TITLE
Group Collaborations should be separated with an ampersand

### ISSUE THREAD

**Issue by vigorousjammer** [Daiz/manga-naming-scheme#1]
Hey there! So, the naming scheme works really well... and it's great for sorting.
However, why do you separate group collaborations with a simple hyphen?
This makes it much more difficult when there's a group name that has a hyphen in it, and it also just doesn't look very good when it's all bunched-up like that.

Here's what I recommend for group collaborations:

_[GroupA & GroupB & GroupC]_

I doubt many groups use an ampersand in their group name, and, in fact, searching on MangaUpdates, I could only find a total of 8 groups with an ampersand in their name. (https://www.mangaupdates.com/groups.html?page=1&search=%26)
Compare that to the **over 600 results** I got when I searched for groups with a hyphen in their name. (https://www.mangaupdates.com/groups.html?page=1&search=-)

As long as there's a space before and after each ampersand, and as long as we still don't allow for spaces in the group names themselves, even the ones that do use an ampersand will still be able to be recognized as a single group.

For example:
_Manga Name [lang] - c001 (v01) [Binggo&CorpTranslations & Fire&IceScans & Manga-Underground]_

Another option is to use a plus sign, and the numbers are actually in favor of this, as can be seen by this search on MangaUpdates (https://www.mangaupdates.com/groups.html?page=1&search=%2B)
However, I just don't really like the way it looks.

For example:
_Manga Name [lang] - c001 (v01) [NoseBleed++ + Daiz + Illuminati-Manga]_

As you can see, it's possible for the plus to come at the end of a group's name, which just looks really messy in this case. This isn't true of ampersands, as there would always be something before & after an ampersand, so the issue can be avoided there.

Anyway, is there a serverside reason for not using one of these symbols? Are you just looking to avoid "%26" or "%2B" strings in your URLs? Or was it simply not considered until now?

**Comment by Daiz** [comment]
Yes, this is a good idea. I kinda winged the initial suggestion of groupnames and shied away from & because of URL encoding, but considering filenames have other special characters there's really no reason to avoid this one either.
