### ISSUE TITLE
What to do about anthologies?

### ISSUE THREAD

**Issue by vigorousjammer** [Daiz/manga-naming-scheme#2]
Hey there, Daiz! So, I ran into another issue recently... For anthology manga such as [Robot](http://bato.to/comic/_/comics/robot-r13684), I'm having trouble figuring out what is the best way to sort stuff... 
Most of what these anthologies publish are one-shots, but especially in the case of Robot, it seems like most users still have a desire to sort each volume in the order the chapters were published, despite the chapters being unrelated.
Now, most users have adopted a chapter numbering system that works per-volume... (for example, volume 1 might have chapters 1-8, and then, volume 2 would have a separate batch of chapters, also numbered 1-8).
However, this style doesn't seem to work for our naming scheme since the chapter number comes first, leaving things to be sorted as following:

Robot - 001 (v01) [Oneshot] [Group Name]
Robot - 001 (v02) [Oneshot] [Group Name]
Robot - 001 (v03) [Oneshot] [Group Name]
Robot - 001 (v04) [Oneshot] [Group Name]
Robot - 002 (v01) [Oneshot] [Group Name]
Robot - 002 (v02) [Oneshot] [Group Name]

and so on...

So, what is the alternative?

I propose perhaps adopting a naming scheme specifically for anthologies that gets rid of chapter numbering, like so:

Robot - (v01x1) [Oneshot] [Extra Information] [Group Name]
Robot - (v01x2) [Oneshot] [Extra Information] [Group Name]
Robot - (v01x3) [Oneshot] [Extra Information] [Group Name]

I suppose we could possibly still go with the "000" method used for other one-shots, and have it be like this:

Robot - 000 (v01x1) [Oneshot] [Extra Information] [Group Name]
Robot - 000 (v01x2) [Oneshot] [Extra Information] [Group Name]
Robot - 000 (v01x3) [Oneshot] [Extra Information] [Group Name]

Although, in my opinion, that's just three extra unneeded characters.

Another good idea would be to have the chapter title in the file name... seeing as they are one-shots, it should be in there somewhere. I propose something like this:

Robot - 000 (v01x1) - Chapter Title [Oneshot] [Extra Information] [Group Name]
Robot - 000 (v01x2) - Chapter Title [Oneshot] [Extra Information] [Group Name]
Robot - 000 (v01x3) - Chapter Title [Oneshot] [Extra Information] [Group Name]

Edit: Another thing I ran into... for oneshots where the source isn't from a magazine, the web, or a numbered volume... should I just use (vol) instead? There's many anthology books out there that collect one-shots from magazines, but since the raws came from a volume I feel like I should still list it as such. What do you think?

**Comment by Daiz** [comment]
Generally speaking, the idea with anthologies would be to title the chapters by the actual name of the oneshot. The fact that it comes from a particular volume of the Robot anthology could then be expressed in extra information. So you'd have names like this:

```
Angels at the Planetarium - 000 (v00) [Oneshot] [Robot v01] [Group Name].zip
Carogna - 000 (v00) [Oneshot] [Robot v01] [Group Name].zip
Wasteland - 000 (v00) [Oneshot] [Robot v01] [Group Name].zip
Dream of the Empty Cage - 000 (v00) [Oneshot] [Robot v01] [Group Name].zip
```

And so on.

However, if you wanted to keep them together, you could still work it out by making the volume information simply a part of the name. So then you'd have:

```
Robot v01 - 001 (v00) [Oneshot] [Group Name].zip
Robot v01 - 002 (v00) [Oneshot] [Group Name].zip
...
Robot v02 - 001 (v00) [Oneshot] [Group Name].zip
Robot v02 - 002 (v00) [Oneshot] [Group Name].zip
```

Which will sort correctly.

You're right that a number-free `(vol)` indicator would be a good idea for something like these in place of a (v00) or such. On the other hand, anthologies, especially ones with numbered releases, could be considered magazines too... for example, one of the Dowman Sayman chapters from a Robot anthology has also released in a Dowman Sayman book.

Yeah, the more I think about it, anthologies would probably be better off just labeled with `(mag)`.

**Comment by vigorousjammer** [comment]
Looks good! Thanks for the clarification! ^_^
